version: '3.5'

name: database-proxy
services:
  crdb:
    image: cockroachdb/cockroach:v22.1.0
    ports:
      - "26257:26257"
      - "8080:8080"
    command: start-single-node --insecure
    volumes:
      - ./init-cockroach.sql:/docker-entrypoint-initdb.d/init.sql
  postgres:
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: database-proxy
    image: postgres:latest
    ports:
      - "5432:5432"
    volumes:
      - ./init-postgres.sql:/docker-entrypoint-initdb.d/init.sql
#  database-proxy:
#    environment:
#      POSTGRES_PASSWORD: admin
#      CRB_PASSWORD:
#    image: universal-database-proxy:0.0.0
#    ports:
#      - "1234:1234"
#      - "5433:5433"
#      - "8000:8000"
#      - "8010:8010"
#    volumes:
#      - ./config.json:/usr/database-proxy/config.json
