name: database-proxy
services:
  crdb:
    image: cockroachdb/cockroach:v22.1.0
    ports:
      - "26257:26257"
      - "8080:8080"
    command: start-single-node --insecure
    volumes:
      - ./init-cockroach.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: cockroach sql --insecure
      interval: 1s
      timeout: 3s
      retries: 5
  postgres:
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: database-proxy
    image: postgres:latest
    ports:
      - "5432:5432"
    volumes:
      - ./init-postgres.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: psql -U postgres
      interval: 1s
      timeout: 3s
      retries: 5
  cassandra:
    image: cassandra:5.0
    ports:
      - "9042:9042"
    environment:
      MAX_HEAP_SIZE: 512M
      HEAP_NEWSIZE: 128M
      CASSANDRA_DC: datacenter1
    healthcheck:
      test: [ "CMD-SHELL", "cqlsh -e 'describe keyspaces' || exit 1" ]
      interval: 10s
      timeout: 10s
      retries: 30
      start_period: 60s
  cassandra-init:
    image: cassandra:5.0
    depends_on:
      cassandra:
        condition: service_healthy
    volumes:
      - ./init-cassandra.cql:/init.cql
    command: cqlsh cassandra -f /init.cql
    restart: on-failure
#  database-proxy:
#    environment:
#      POSTGRES_HOSTS: postgres:5432
#      POSTGRES_PASSWORD: admin
#      CRB_HOSTS: crdb:26257
#      CRB_PASSWORD:
#      CASSANDRA_HOSTS: cassandra:9042
#      CASSANDRA_PASSWORD: cassandra
#    image: mcadecio/universal-database-proxy-rest:1.0.3
#    depends_on:
#      postgres:
#        condition: service_healthy
#      crdb:
#        condition: service_healthy
#      cassandra:
#        condition: service_healthy
#    ports:
#      - "8000:8000"
#      - "8010:8010"
#      - "8020:8020"
#    volumes:
#      - ./config.json:/usr/database-proxy/config.json
