package com.dercio.database_proxy.cockroach;

import com.dercio.database_proxy.common.database.DatabaseConfig;
import com.google.inject.*;
import com.google.inject.Module;
import com.google.inject.name.Names;
import io.vertx.core.Vertx;
import io.vertx.jdbcclient.JDBCConnectOptions;
import org.junit.jupiter.api.Test;

import java.time.Clock;
import java.util.Map;

import static org.junit.jupiter.api.Assertions.*;

class CockroachModuleTest {
    private final Injector injector = Guice.createInjector(new CockroachModule(), createModuleSetup(createCrApiConfig()));

    @Test
    void shouldConfigureCrConnectOptionsBasedOnEnvVariables() {
        var jdbcConnectOptions = injector.getInstance(Key.get(JDBCConnectOptions.class, Names.named("cr.connection.options")));

        assertAll(
                () -> assertEquals("jdbc:postgresql://localhost:2020/default?", jdbcConnectOptions.getJdbcUrl()),
                () -> assertEquals("default", jdbcConnectOptions.getDatabase()),
                () -> assertEquals("root", jdbcConnectOptions.getUser()),
                () -> assertEquals("pass", jdbcConnectOptions.getPassword()),
                () -> assertFalse(jdbcConnectOptions.isAutoGeneratedKeys())
        );
    }

    @Test
    void shouldConfigureCrConnectOptionsUsingProvidedProperties() {
        var crApiConfig = injector.getInstance(CrApiConfig.class).getDatabase();
        crApiConfig.setDatabaseName("database");
        crApiConfig.setHost("192.0.0.1");
        crApiConfig.setUsername("main");
        crApiConfig.setPassword("1234");
        crApiConfig.setTargetServerType("primary");


        var jdbcConnectOptions = injector.getInstance(Key.get(JDBCConnectOptions.class, Names.named("cr.connection.options")));

        assertAll(
                () -> assertEquals("jdbc:postgresql://192.0.0.1:2020/database?targetServerType=primary",
                        jdbcConnectOptions.getJdbcUrl()),
                () -> assertEquals("database", jdbcConnectOptions.getDatabase()),
                () -> assertEquals("main", jdbcConnectOptions.getUser()),
                () -> assertEquals("1234", jdbcConnectOptions.getPassword())
        );
    }

    @Test
    void shouldConfigureCrConnectOptionsUsingProvidedJdbcUrl() {
        var pgApiConfig = injector.getInstance(CrApiConfig.class).getDatabase();
        pgApiConfig.setJdbcUrl("jdbc:postgresql://localhost:2020/default?ssl=true");

        var jdbcConnectOptions = injector.getInstance(Key.get(JDBCConnectOptions.class, Names.named("cr.connection.options")));

        assertEquals("jdbc:postgresql://localhost:2020/default?ssl=true", jdbcConnectOptions.getJdbcUrl());
    }

    private CrApiConfig createCrApiConfig() {
        CrApiConfig crApiConfig = new CrApiConfig();
        crApiConfig.setEnabled(true);
        DatabaseConfig databaseConfig = new DatabaseConfig();
        databaseConfig.setHost("CR_HOST");
        databaseConfig.setUsername("CR_USER");
        databaseConfig.setPassword("CR_PASS");
        databaseConfig.setDatabaseName("CR_DBNAME");
        databaseConfig.setPort(2020);
        crApiConfig.setDatabase(databaseConfig);
        return crApiConfig;
    }

    private Module createModuleSetup(CrApiConfig crApiConfig) {
        return binder -> {
            var envVariables = Map.of(
                    "CR_HOST", "localhost",
                    "CR_USER", "root",
                    "CR_PASS", "pass",
                    "CR_DBNAME", "default"
            );

            binder.bind(new TypeLiteral<Map<String, String>>() {
                    })
                    .annotatedWith(Names.named("system.env.variables"))
                    .toInstance(envVariables);
            binder.bind(Clock.class).toInstance(Clock.systemDefaultZone());
            binder.bind(CrApiConfig.class).toInstance(crApiConfig);
            binder.bind(Vertx.class).toInstance(Vertx.vertx());
        };
    }

}