package com.dercio.database_proxy.postgres;

import com.dercio.database_proxy.common.database.DatabaseConfig;
import io.vertx.jdbcclient.JDBCConnectOptions;
import org.apache.commons.lang3.ObjectUtils;

import java.util.Map;
import java.util.Optional;
import java.util.StringJoiner;

public class PgJdbcConnectOptionsFactory {

    public JDBCConnectOptions create(DatabaseConfig databaseConfig, Map<String, String> envVariables) {
        var username = resolveValue(databaseConfig.getUsername(), envVariables);
        var password = resolveValue(databaseConfig.getPassword(), envVariables);
        var databaseName = resolveValue(databaseConfig.getDatabaseName(), envVariables);
        var jdbcUrl = buildJdbcUrl(databaseConfig, databaseName, envVariables);

        return new JDBCConnectOptions()
                .setJdbcUrl(jdbcUrl)
                .setUser(username)
                .setPassword(password)
                .setDatabase(databaseName)
                .setAutoGeneratedKeys(false);
    }

    private String buildJdbcUrl(DatabaseConfig databaseConfig, String databaseName, Map<String, String> envVariables) {
        var targetServerType = databaseConfig.getTargetServerType();
        var configuredJdbcUrl = databaseConfig.getJdbcUrl();

        if (configuredJdbcUrl != null && !configuredJdbcUrl.isBlank()) {
            return configuredJdbcUrl;
        }

        var host = resolveValue(databaseConfig.getHost(), envVariables);
        StringJoiner jdbcUrlBuilder = new StringJoiner("");
        jdbcUrlBuilder.add("jdbc:postgresql://");
        jdbcUrlBuilder.add(host).add(":");
        jdbcUrlBuilder.add(databaseConfig.getPort().toString());
        jdbcUrlBuilder.add("/");
        jdbcUrlBuilder.add(databaseName);
        jdbcUrlBuilder.add("?");

        if (targetServerType != null && !targetServerType.isBlank()) {
            jdbcUrlBuilder.add("targetServerType=").add(targetServerType);
        }

        if (databaseConfig.isSslEnabled()) {
            jdbcUrlBuilder.add("&ssl=true");
            var sslCertPath = databaseConfig.getSslCertPath();
            ObjectUtils.requireNonEmpty(sslCertPath,
                    "To create an ssl connection with the Postgres Server a valid ssl certificate needs to be provided");
            jdbcUrlBuilder.add("&sslrootcert=").add(sslCertPath);
        }
        return jdbcUrlBuilder.toString();
    }

    private String resolveValue(String value, Map<String, String> envVariables) {
        return Optional.ofNullable(value)
                .orElse(envVariables.get(value));
    }

}
